# Generated by Django 3.1.1 on 2023-05-10 06:36

import autoslug.fields
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('product_id', models.CharField(max_length=250, verbose_name='Product Id')),
                ('product_name', models.CharField(max_length=250, verbose_name='The Name Of The Poultry Product')),
                ('description', models.TextField(verbose_name='Product Description')),
                ('unit_price', models.FloatField(verbose_name='Unit Price Dollars')),
                ('quantity_in_stock', models.IntegerField(default=0, verbose_name='Units In Stock')),
                ('unit_of_measure', models.CharField(max_length=4, verbose_name='Unit Of Measurement')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='product_id', unique=True, verbose_name='product_address')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
