# Generated by Django 3.1.1 on 2023-05-15 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20230515_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='id',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.CharField(max_length=250, primary_key=True, serialize=False, verbose_name='Product Id'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=250, unique=True, verbose_name='The Name Of The Poultry Product'),
        ),
    ]
